name: TechFeed
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - feedparser
  - feedgen
  - scikit-learn
  - PyYAML
  - python-dateutil
  - beautifulsoup4
  - tenacity
  - requests
  - pip
  - pip:
    - fugashi
    - unidic-lite
